name: pull-request-workflow

on:
  pull_request:
    # Ignore main because if code pushed to main, we know it has been tested already via this flow
    branches-ignore:
      - 'main'
    # Changes that don't require a CI/CD run
    paths-ignore:
      - 'README.md'

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: yarn ci:lint:all
      - run: yarn ci:test:all
      - run: yarn ci:build:all
